export const FETCH_PMOVIES_REQUEST = 'FETCH_PMOVIES_REQUEST'
export const FETCH_PMOVIES_SUCCESS = 'FETCH_PMOVIES_SUCCESS'
export const FETCH_PMOVIES_FAILURE = 'FETCH_PMOVIES_FAILURE'

export const FETCH_TMOVIES_REQUEST = 'FETCH_TMOVIES_REQUEST'
export const FETCH_TMOVIES_SUCCESS = 'FETCH_TMOVIES_SUCCESS'
export const FETCH_TMOVIES_FAILURE = 'FETCH_TMOVIES_FAILURE'

export const FETCH_UMOVIES_REQUEST = 'FETCH_UMOVIES_REQUEST'
export const FETCH_UMOVIES_SUCCESS = 'FETCH_UMOVIES_SUCCESS'
export const FETCH_UMOVIES_FAILURE = 'FETCH_UMOVIES_FAILURE'

export const url = 'https://image.tmdb.org/t/p/w500'