export const FETCH_PTVSHOWS_REQUEST = 'FETCH_PTVSHOWS_REQUEST'
export const FETCH_PTVSHOWS_SUCCESS = 'FETCH_PTVSHOWS_SUCCESS'
export const FETCH_PTVSHOWS_FAILURE = 'FETCH_PTVSHOWS_FAILURE'

export const FETCH_AIRTVSHOWS_REQUEST = 'FETCH_AIRTVSHOWS_REQUEST'
export const FETCH_AIRTVSHOWS_SUCCESS = 'FETCH_AIRTVSHOWS_SUCCESS'
export const FETCH_AIRTVSHOWS_FAILURE = 'FETCH_AIRTVSHOWS_FAILURE'

export const FETCH_LTVSHOWS_REQUEST = 'FETCH_LTVSHOWS_REQUEST'
export const FETCH_LTVSHOWS_SUCCESS = 'FETCH_LTVSHOWS_SUCCESS'
export const FETCH_LTVSHOWS_FAILURE = 'FETCH_LTVSHOWS_FAILURE'

export const url = 'https://image.tmdb.org/t/p/w500'