export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const FETCH_TVSHOWS_REQUEST = "FETCH_TVSHOWS_REQUEST";
export const FETCH_TVSHOWS_SUCCESS = "FETCH_TVSHOWS_SUCCESS";
export const FETCH_TVSHOWS_FAILURE = "FETCH_TVSHOWS_FAILURE";

export const APIKEY = "0451e553a464ab7929fee2e705dab05e";
